---
- name: Création du dossier de config de Code Server
  ansible.builtin.file:
    path: /home/tristan/codeserver
    state: directory
    mode: '0755'

- name: Création et lancement du conteneur Code Server
  community.docker.docker_compose:
    project_name: code-server
    definition:
      version: '2'
      services:
        code-server:
          image: lscr.io/linuxserver/code-server:latest
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
      #       - PASSWORD=password #optional
      #       - HASHED_PASSWORD= #optional
      #       - SUDO_PASSWORD=password #optional 
      #       - SUDO_PASSWORD_HASH= #optional
      #      - PROXY_DOMAIN=code.the-barn.fr #optional
      #       - DEFAULT_WORKSPACE=/config/workspace #optional
          volumes:
            - /home/tristan/codeserver:/config
            - /home/tristan:/home
          ports:
            - 8443:8443
          restart: unless-stopped
