---

- hosts: localhost

  vars:
    pip_install_packages:
      - name: docker
    
  roles:
    - name: geerlingguy.pip
      src: https://github.com/geerlingguy/ansible-role-pip.git
      version: 3.0.0
      become: true
    - geerlingguy.docker
    - code_server
